/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrganisatorischeEenheid'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/OrganisatorischeEenheid'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.BetrokkenenApi = factory(root.ZaakregistratiecomponentZrcApi.ApiClient, root.ZaakregistratiecomponentZrcApi.OrganisatorischeEenheid);
  }
}(this, function(ApiClient, OrganisatorischeEenheid) {
  'use strict';

  /**
   * Betrokkenen service.
   * @module api/BetrokkenenApi
   * @version 1
   */

  /**
   * Constructs a new BetrokkenenApi. 
   * @alias module:api/BetrokkenenApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the betrokkenenByIdGet operation.
     * @callback module:api/BetrokkenenApi~betrokkenenByIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/OrganisatorischeEenheid} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * organisatorischeeenheid_read
     * 
     * @param {Number} id A unique integer value identifying this Organisatorische eenheid.
     * @param {module:api/BetrokkenenApi~betrokkenenByIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/OrganisatorischeEenheid}
     */
    this.betrokkenenByIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling betrokkenenByIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = OrganisatorischeEenheid;

      return this.apiClient.callApi(
        '/betrokkenen/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
