/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/KlantContact'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/KlantContact'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.KlantcontactenApi = factory(root.ZaakregistratiecomponentZrcApi.ApiClient, root.ZaakregistratiecomponentZrcApi.KlantContact);
  }
}(this, function(ApiClient, KlantContact) {
  'use strict';

  /**
   * Klantcontacten service.
   * @module api/KlantcontactenApi
   * @version 1
   */

  /**
   * Constructs a new KlantcontactenApi. 
   * @alias module:api/KlantcontactenApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the klantcontactenByIdGet operation.
     * @callback module:api/KlantcontactenApi~klantcontactenByIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KlantContact} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * klantcontact_read
     * Geef de details van een klantcontact voor een ZAAK.
     * @param {Number} id A unique integer value identifying this klantcontact.
     * @param {module:api/KlantcontactenApi~klantcontactenByIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KlantContact}
     */
    this.klantcontactenByIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling klantcontactenByIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = KlantContact;

      return this.apiClient.callApi(
        '/klantcontacten/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the klantcontactenPost operation.
     * @callback module:api/KlantcontactenApi~klantcontactenPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KlantContact} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * klantcontact_create
     * Registreer een klantcontact bij een ZAAK.  Indien geen identificatie gegeven is, dan wordt deze automatisch gegenereerd.
     * @param {module:model/KlantContact} body 
     * @param {module:api/KlantcontactenApi~klantcontactenPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KlantContact}
     */
    this.klantcontactenPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling klantcontactenPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = KlantContact;

      return this.apiClient.callApi(
        '/klantcontacten', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
