/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ZaakObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ZaakObject'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.ZaakobjectenApi = factory(root.ZaakregistratiecomponentZrcApi.ApiClient, root.ZaakregistratiecomponentZrcApi.ZaakObject);
  }
}(this, function(ApiClient, ZaakObject) {
  'use strict';

  /**
   * Zaakobjecten service.
   * @module api/ZaakobjectenApi
   * @version 1
   */

  /**
   * Constructs a new ZaakobjectenApi. 
   * @alias module:api/ZaakobjectenApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the zaakobjectenByIdGet operation.
     * @callback module:api/ZaakobjectenApi~zaakobjectenByIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ZaakObject} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * zaakobject_read
     * Geef de details van een ZAAKOBJECT relatie.
     * @param {Number} id A unique integer value identifying this zaakobject.
     * @param {module:api/ZaakobjectenApi~zaakobjectenByIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ZaakObject}
     */
    this.zaakobjectenByIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling zaakobjectenByIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ZaakObject;

      return this.apiClient.callApi(
        '/zaakobjecten/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the zaakobjectenPost operation.
     * @callback module:api/ZaakobjectenApi~zaakobjectenPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ZaakObject} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * zaakobject_create
     * Registreer een ZAAKOBJECT relatie.
     * @param {module:model/ZaakObject} body 
     * @param {module:api/ZaakobjectenApi~zaakobjectenPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ZaakObject}
     */
    this.zaakobjectenPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling zaakobjectenPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ZaakObject;

      return this.apiClient.callApi(
        '/zaakobjecten', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
