/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Zaak', 'model/ZaakEigenschap'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Zaak'), require('../model/ZaakEigenschap'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.ZakenApi = factory(root.ZaakregistratiecomponentZrcApi.ApiClient, root.ZaakregistratiecomponentZrcApi.Zaak, root.ZaakregistratiecomponentZrcApi.ZaakEigenschap);
  }
}(this, function(ApiClient, Zaak, ZaakEigenschap) {
  'use strict';

  /**
   * Zaken service.
   * @module api/ZakenApi
   * @version 1
   */

  /**
   * Constructs a new ZakenApi. 
   * @alias module:api/ZakenApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the zakenByIdGet operation.
     * @callback module:api/ZakenApi~zakenByIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Zaak} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * zaak_read
     * Opvragen en bewerken van ZAAKen.
     * @param {Number} id A unique integer value identifying this zaak.
     * @param {module:api/ZakenApi~zakenByIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Zaak}
     */
    this.zakenByIdGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling zakenByIdGet");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Zaak;

      return this.apiClient.callApi(
        '/zaken/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the zakenPost operation.
     * @callback module:api/ZakenApi~zakenPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Zaak} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * zaak_create
     * Maak een ZAAK aan.  Indien geen zaakidentificatie gegeven is, dan wordt deze automatisch gegenereerd.
     * @param {module:model/Zaak} body 
     * @param {module:api/ZakenApi~zakenPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Zaak}
     */
    this.zakenPost = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling zakenPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Zaak;

      return this.apiClient.callApi(
        '/zaken', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the zakenZaakeigenschappenByZaakPkAndIdGet operation.
     * @callback module:api/ZakenApi~zakenZaakeigenschappenByZaakPkAndIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ZaakEigenschap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * zaakeigenschap_read
     * Geef de details van ZaakEigenschap voor een ZAAK.
     * @param {Number} id A unique integer value identifying this zaakeigenschap.
     * @param {String} zaakPk 
     * @param {module:api/ZakenApi~zakenZaakeigenschappenByZaakPkAndIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ZaakEigenschap}
     */
    this.zakenZaakeigenschappenByZaakPkAndIdGet = function(id, zaakPk, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling zakenZaakeigenschappenByZaakPkAndIdGet");
      }

      // verify the required parameter 'zaakPk' is set
      if (zaakPk === undefined || zaakPk === null) {
        throw new Error("Missing the required parameter 'zaakPk' when calling zakenZaakeigenschappenByZaakPkAndIdGet");
      }


      var pathParams = {
        'id': id,
        'zaak_pk': zaakPk
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ZaakEigenschap;

      return this.apiClient.callApi(
        '/zaken/{zaak_pk}/zaakeigenschappen/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the zakenZaakeigenschappenByZaakPkGet operation.
     * @callback module:api/ZakenApi~zakenZaakeigenschappenByZaakPkGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ZaakEigenschap>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * zaakeigenschap_list
     * Geef een collectie van eigenschappen behorend bij een ZAAK.
     * @param {String} zaakPk 
     * @param {module:api/ZakenApi~zakenZaakeigenschappenByZaakPkGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ZaakEigenschap>}
     */
    this.zakenZaakeigenschappenByZaakPkGet = function(zaakPk, callback) {
      var postBody = null;

      // verify the required parameter 'zaakPk' is set
      if (zaakPk === undefined || zaakPk === null) {
        throw new Error("Missing the required parameter 'zaakPk' when calling zakenZaakeigenschappenByZaakPkGet");
      }


      var pathParams = {
        'zaak_pk': zaakPk
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ZaakEigenschap];

      return this.apiClient.callApi(
        '/zaken/{zaak_pk}/zaakeigenschappen', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the zakenZaakeigenschappenByZaakPkPost operation.
     * @callback module:api/ZakenApi~zakenZaakeigenschappenByZaakPkPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ZaakEigenschap} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * zaakeigenschap_create
     * Registreer een eigenschap van een ZAAK.
     * @param {String} zaakPk 
     * @param {module:model/ZaakEigenschap} body 
     * @param {module:api/ZakenApi~zakenZaakeigenschappenByZaakPkPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ZaakEigenschap}
     */
    this.zakenZaakeigenschappenByZaakPkPost = function(zaakPk, body, callback) {
      var postBody = body;

      // verify the required parameter 'zaakPk' is set
      if (zaakPk === undefined || zaakPk === null) {
        throw new Error("Missing the required parameter 'zaakPk' when calling zakenZaakeigenschappenByZaakPkPost");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling zakenZaakeigenschappenByZaakPkPost");
      }


      var pathParams = {
        'zaak_pk': zaakPk
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['auth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ZaakEigenschap;

      return this.apiClient.callApi(
        '/zaken/{zaak_pk}/zaakeigenschappen', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
