/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/KlantContact', 'model/OrganisatorischeEenheid', 'model/Rol', 'model/Rolomschrijving', 'model/RolomschrijvingGeneriek', 'model/Status', 'model/Zaak', 'model/ZaakEigenschap', 'model/ZaakObject', 'api/BetrokkenenApi', 'api/KlantcontactenApi', 'api/RollenApi', 'api/StatussenApi', 'api/ZaakobjectenApi', 'api/ZakenApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/KlantContact'), require('./model/OrganisatorischeEenheid'), require('./model/Rol'), require('./model/Rolomschrijving'), require('./model/RolomschrijvingGeneriek'), require('./model/Status'), require('./model/Zaak'), require('./model/ZaakEigenschap'), require('./model/ZaakObject'), require('./api/BetrokkenenApi'), require('./api/KlantcontactenApi'), require('./api/RollenApi'), require('./api/StatussenApi'), require('./api/ZaakobjectenApi'), require('./api/ZakenApi'));
  }
}(function(ApiClient, KlantContact, OrganisatorischeEenheid, Rol, Rolomschrijving, RolomschrijvingGeneriek, Status, Zaak, ZaakEigenschap, ZaakObject, BetrokkenenApi, KlantcontactenApi, RollenApi, StatussenApi, ZaakobjectenApi, ZakenApi) {
  'use strict';

  /**
   * Een_API_om_een_zaakregistratiecomponent_te_benaderen.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var ZaakregistratiecomponentZrcApi = require('index'); // See note below*.
   * var xxxSvc = new ZaakregistratiecomponentZrcApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new ZaakregistratiecomponentZrcApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new ZaakregistratiecomponentZrcApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new ZaakregistratiecomponentZrcApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The KlantContact model constructor.
     * @property {module:model/KlantContact}
     */
    KlantContact: KlantContact,
    /**
     * The OrganisatorischeEenheid model constructor.
     * @property {module:model/OrganisatorischeEenheid}
     */
    OrganisatorischeEenheid: OrganisatorischeEenheid,
    /**
     * The Rol model constructor.
     * @property {module:model/Rol}
     */
    Rol: Rol,
    /**
     * The Rolomschrijving model constructor.
     * @property {module:model/Rolomschrijving}
     */
    Rolomschrijving: Rolomschrijving,
    /**
     * The RolomschrijvingGeneriek model constructor.
     * @property {module:model/RolomschrijvingGeneriek}
     */
    RolomschrijvingGeneriek: RolomschrijvingGeneriek,
    /**
     * The Status model constructor.
     * @property {module:model/Status}
     */
    Status: Status,
    /**
     * The Zaak model constructor.
     * @property {module:model/Zaak}
     */
    Zaak: Zaak,
    /**
     * The ZaakEigenschap model constructor.
     * @property {module:model/ZaakEigenschap}
     */
    ZaakEigenschap: ZaakEigenschap,
    /**
     * The ZaakObject model constructor.
     * @property {module:model/ZaakObject}
     */
    ZaakObject: ZaakObject,
    /**
     * The BetrokkenenApi service constructor.
     * @property {module:api/BetrokkenenApi}
     */
    BetrokkenenApi: BetrokkenenApi,
    /**
     * The KlantcontactenApi service constructor.
     * @property {module:api/KlantcontactenApi}
     */
    KlantcontactenApi: KlantcontactenApi,
    /**
     * The RollenApi service constructor.
     * @property {module:api/RollenApi}
     */
    RollenApi: RollenApi,
    /**
     * The StatussenApi service constructor.
     * @property {module:api/StatussenApi}
     */
    StatussenApi: StatussenApi,
    /**
     * The ZaakobjectenApi service constructor.
     * @property {module:api/ZaakobjectenApi}
     */
    ZaakobjectenApi: ZaakobjectenApi,
    /**
     * The ZakenApi service constructor.
     * @property {module:api/ZakenApi}
     */
    ZakenApi: ZakenApi
  };

  return exports;
}));
