/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.OrganisatorischeEenheid = factory(root.ZaakregistratiecomponentZrcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OrganisatorischeEenheid model module.
   * @module model/OrganisatorischeEenheid
   * @version 1
   */

  /**
   * Constructs a new <code>OrganisatorischeEenheid</code>.
   * @alias module:model/OrganisatorischeEenheid
   * @class
   * @param organisatieEenheidIdentificatie {String} Een korte identificatie van de organisatorische eenheid.
   * @param organisatieIdentificatie {Number} Het RSIN van de organisatie zijnde een Niet-natuurlijk persoon waarvan de ORGANISATORISCHE EENHEID deel uit maakt.
   * @param datumOntstaan {Date} De datum wrop de organisatorische eenheid is ontstaan.
   * @param naam {String} De feitelijke naam van de organisatorische eenheid.
   */
  var exports = function(organisatieEenheidIdentificatie, organisatieIdentificatie, datumOntstaan, naam) {
    var _this = this;

    _this['organisatieEenheidIdentificatie'] = organisatieEenheidIdentificatie;
    _this['organisatieIdentificatie'] = organisatieIdentificatie;
    _this['datumOntstaan'] = datumOntstaan;
    _this['naam'] = naam;

  };

  /**
   * Constructs a <code>OrganisatorischeEenheid</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrganisatorischeEenheid} obj Optional instance to populate.
   * @return {module:model/OrganisatorischeEenheid} The populated <code>OrganisatorischeEenheid</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('organisatieEenheidIdentificatie')) {
        obj['organisatieEenheidIdentificatie'] = ApiClient.convertToType(data['organisatieEenheidIdentificatie'], 'String');
      }
      if (data.hasOwnProperty('organisatieIdentificatie')) {
        obj['organisatieIdentificatie'] = ApiClient.convertToType(data['organisatieIdentificatie'], 'Number');
      }
      if (data.hasOwnProperty('datumOntstaan')) {
        obj['datumOntstaan'] = ApiClient.convertToType(data['datumOntstaan'], 'Date');
      }
      if (data.hasOwnProperty('naam')) {
        obj['naam'] = ApiClient.convertToType(data['naam'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }

  /**
   * Een korte identificatie van de organisatorische eenheid.
   * @member {String} organisatieEenheidIdentificatie
   */
  exports.prototype['organisatieEenheidIdentificatie'] = undefined;
  /**
   * Het RSIN van de organisatie zijnde een Niet-natuurlijk persoon waarvan de ORGANISATORISCHE EENHEID deel uit maakt.
   * @member {Number} organisatieIdentificatie
   */
  exports.prototype['organisatieIdentificatie'] = undefined;
  /**
   * De datum wrop de organisatorische eenheid is ontstaan.
   * @member {Date} datumOntstaan
   */
  exports.prototype['datumOntstaan'] = undefined;
  /**
   * De feitelijke naam van de organisatorische eenheid.
   * @member {String} naam
   */
  exports.prototype['naam'] = undefined;
  /**
   * 
   * @member {String} url
   */
  exports.prototype['url'] = undefined;



  return exports;
}));


