/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Rolomschrijving', 'model/RolomschrijvingGeneriek'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Rolomschrijving'), require('./RolomschrijvingGeneriek'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.Rol = factory(root.ZaakregistratiecomponentZrcApi.ApiClient, root.ZaakregistratiecomponentZrcApi.Rolomschrijving, root.ZaakregistratiecomponentZrcApi.RolomschrijvingGeneriek);
  }
}(this, function(ApiClient, Rolomschrijving, RolomschrijvingGeneriek) {
  'use strict';




  /**
   * The Rol model module.
   * @module model/Rol
   * @version 1
   */

  /**
   * Constructs a new <code>Rol</code>.
   * @alias module:model/Rol
   * @class
   * @param zaak {String} 
   * @param betrokkene {String} 
   * @param rolomschrijving {module:model/Rolomschrijving} 
   * @param rolomschrijvingGeneriek {module:model/RolomschrijvingGeneriek} 
   * @param roltoelichting {String} 
   */
  var exports = function(zaak, betrokkene, rolomschrijving, rolomschrijvingGeneriek, roltoelichting) {
    var _this = this;

    _this['zaak'] = zaak;
    _this['betrokkene'] = betrokkene;
    _this['rolomschrijving'] = rolomschrijving;
    _this['rolomschrijvingGeneriek'] = rolomschrijvingGeneriek;
    _this['roltoelichting'] = roltoelichting;

  };

  /**
   * Constructs a <code>Rol</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Rol} obj Optional instance to populate.
   * @return {module:model/Rol} The populated <code>Rol</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('zaak')) {
        obj['zaak'] = ApiClient.convertToType(data['zaak'], 'String');
      }
      if (data.hasOwnProperty('betrokkene')) {
        obj['betrokkene'] = ApiClient.convertToType(data['betrokkene'], 'String');
      }
      if (data.hasOwnProperty('rolomschrijving')) {
        obj['rolomschrijving'] = Rolomschrijving.constructFromObject(data['rolomschrijving']);
      }
      if (data.hasOwnProperty('rolomschrijvingGeneriek')) {
        obj['rolomschrijvingGeneriek'] = RolomschrijvingGeneriek.constructFromObject(data['rolomschrijvingGeneriek']);
      }
      if (data.hasOwnProperty('roltoelichting')) {
        obj['roltoelichting'] = ApiClient.convertToType(data['roltoelichting'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} zaak
   */
  exports.prototype['zaak'] = undefined;
  /**
   * 
   * @member {String} betrokkene
   */
  exports.prototype['betrokkene'] = undefined;
  /**
   * @member {module:model/Rolomschrijving} rolomschrijving
   */
  exports.prototype['rolomschrijving'] = undefined;
  /**
   * @member {module:model/RolomschrijvingGeneriek} rolomschrijvingGeneriek
   */
  exports.prototype['rolomschrijvingGeneriek'] = undefined;
  /**
   * 
   * @member {String} roltoelichting
   */
  exports.prototype['roltoelichting'] = undefined;
  /**
   * 
   * @member {String} url
   */
  exports.prototype['url'] = undefined;



  return exports;
}));


