/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.RolomschrijvingGeneriek = factory(root.ZaakregistratiecomponentZrcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class RolomschrijvingGeneriek.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "Adviseur"
     * @const
     */
    "Adviseur": "Adviseur",
    /**
     * value: "Behandelaar"
     * @const
     */
    "Behandelaar": "Behandelaar",
    /**
     * value: "Belanghebbende"
     * @const
     */
    "Belanghebbende": "Belanghebbende",
    /**
     * value: "Beslisser"
     * @const
     */
    "Beslisser": "Beslisser",
    /**
     * value: "Initiator"
     * @const
     */
    "Initiator": "Initiator",
    /**
     * value: "Klantcontacter"
     * @const
     */
    "Klantcontacter": "Klantcontacter",
    /**
     * value: "Zaakcoördinator"
     * @const
     */
    "Zaakcoördinator": "Zaakcoördinator",
    /**
     * value: "Mede-initiator"
     * @const
     */
    "Mede-initiator": "Mede-initiator"  };

  /**
   * Returns a <code>RolomschrijvingGeneriek</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/RolomschrijvingGeneriek} The enum <code>RolomschrijvingGeneriek</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


