/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.Status = factory(root.ZaakregistratiecomponentZrcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Status model module.
   * @module model/Status
   * @version 1
   */

  /**
   * Constructs a new <code>Status</code>.
   * @alias module:model/Status
   * @class
   * @param zaak {String} 
   * @param statusType {String} 
   * @param datumStatusGezet {Date} De datum waarop de ZAAK de status heeft verkregen.
   */
  var exports = function(zaak, statusType, datumStatusGezet) {
    var _this = this;

    _this['zaak'] = zaak;
    _this['statusType'] = statusType;
    _this['datumStatusGezet'] = datumStatusGezet;


  };

  /**
   * Constructs a <code>Status</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Status} obj Optional instance to populate.
   * @return {module:model/Status} The populated <code>Status</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('zaak')) {
        obj['zaak'] = ApiClient.convertToType(data['zaak'], 'String');
      }
      if (data.hasOwnProperty('statusType')) {
        obj['statusType'] = ApiClient.convertToType(data['statusType'], 'String');
      }
      if (data.hasOwnProperty('datumStatusGezet')) {
        obj['datumStatusGezet'] = ApiClient.convertToType(data['datumStatusGezet'], 'Date');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('statustoelichting')) {
        obj['statustoelichting'] = ApiClient.convertToType(data['statustoelichting'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} zaak
   */
  exports.prototype['zaak'] = undefined;
  /**
   * 
   * @member {String} statusType
   */
  exports.prototype['statusType'] = undefined;
  /**
   * De datum waarop de ZAAK de status heeft verkregen.
   * @member {Date} datumStatusGezet
   */
  exports.prototype['datumStatusGezet'] = undefined;
  /**
   * 
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * Een, voor de initiator van de zaak relevante, toelichting op de status van een zaak.
   * @member {String} statustoelichting
   */
  exports.prototype['statustoelichting'] = undefined;



  return exports;
}));


