/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.ZaakEigenschap = factory(root.ZaakregistratiecomponentZrcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ZaakEigenschap model module.
   * @module model/ZaakEigenschap
   * @version 1
   */

  /**
   * Constructs a new <code>ZaakEigenschap</code>.
   * @alias module:model/ZaakEigenschap
   * @class
   * @param zaak {String} 
   * @param eigenschap {String} URL naar de eigenschap in het ZTC
   * @param waarde {String} 
   */
  var exports = function(zaak, eigenschap, waarde) {
    var _this = this;

    _this['zaak'] = zaak;
    _this['eigenschap'] = eigenschap;
    _this['waarde'] = waarde;

  };

  /**
   * Constructs a <code>ZaakEigenschap</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ZaakEigenschap} obj Optional instance to populate.
   * @return {module:model/ZaakEigenschap} The populated <code>ZaakEigenschap</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('zaak')) {
        obj['zaak'] = ApiClient.convertToType(data['zaak'], 'String');
      }
      if (data.hasOwnProperty('eigenschap')) {
        obj['eigenschap'] = ApiClient.convertToType(data['eigenschap'], 'String');
      }
      if (data.hasOwnProperty('waarde')) {
        obj['waarde'] = ApiClient.convertToType(data['waarde'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} zaak
   */
  exports.prototype['zaak'] = undefined;
  /**
   * URL naar de eigenschap in het ZTC
   * @member {String} eigenschap
   */
  exports.prototype['eigenschap'] = undefined;
  /**
   * 
   * @member {String} waarde
   */
  exports.prototype['waarde'] = undefined;
  /**
   * 
   * @member {String} url
   */
  exports.prototype['url'] = undefined;



  return exports;
}));


