/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.ZaakObject = factory(root.ZaakregistratiecomponentZrcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ZaakObject model module.
   * @module model/ZaakObject
   * @version 1
   */

  /**
   * Constructs a new <code>ZaakObject</code>.
   * @alias module:model/ZaakObject
   * @class
   * @param zaak {String} 
   * @param _object {String} URL naar de resource die het OBJECT beschrijft.
   */
  var exports = function(zaak, _object) {
    var _this = this;

    _this['zaak'] = zaak;
    _this['object'] = _object;


  };

  /**
   * Constructs a <code>ZaakObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ZaakObject} obj Optional instance to populate.
   * @return {module:model/ZaakObject} The populated <code>ZaakObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('zaak')) {
        obj['zaak'] = ApiClient.convertToType(data['zaak'], 'String');
      }
      if (data.hasOwnProperty('object')) {
        obj['object'] = ApiClient.convertToType(data['object'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('relatieomschrijving')) {
        obj['relatieomschrijving'] = ApiClient.convertToType(data['relatieomschrijving'], 'String');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {String} zaak
   */
  exports.prototype['zaak'] = undefined;
  /**
   * URL naar de resource die het OBJECT beschrijft.
   * @member {String} object
   */
  exports.prototype['object'] = undefined;
  /**
   * 
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * Omschrijving van de betrekking tussen de ZAAK en het OBJECT.
   * @member {String} relatieomschrijving
   */
  exports.prototype['relatieomschrijving'] = undefined;



  return exports;
}));


