/**
 * Zaakregistratiecomponent (ZRC) API
 * Een API om een zaakregistratiecomponent te benaderen
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ZaakregistratiecomponentZrcApi) {
      root.ZaakregistratiecomponentZrcApi = {};
    }
    root.ZaakregistratiecomponentZrcApi.Zaak = factory(root.ZaakregistratiecomponentZrcApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Zaak model module.
   * @module model/Zaak
   * @version 1
   */

  /**
   * Constructs a new <code>Zaak</code>.
   * @alias module:model/Zaak
   * @class
   * @param zaaktype {String} URL naar het zaaktype in de CATALOGUS waar deze voorkomt
   * @param registratiedatum {Date} De datum waarop de zaakbehandelende organisatie de ZAAK heeft geregistreerd
   */
  var exports = function(zaaktype, registratiedatum) {
    var _this = this;

    _this['zaaktype'] = zaaktype;
    _this['registratiedatum'] = registratiedatum;





  };

  /**
   * Constructs a <code>Zaak</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Zaak} obj Optional instance to populate.
   * @return {module:model/Zaak} The populated <code>Zaak</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('zaaktype')) {
        obj['zaaktype'] = ApiClient.convertToType(data['zaaktype'], 'String');
      }
      if (data.hasOwnProperty('registratiedatum')) {
        obj['registratiedatum'] = ApiClient.convertToType(data['registratiedatum'], 'Date');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('zaakidentificatie')) {
        obj['zaakidentificatie'] = ApiClient.convertToType(data['zaakidentificatie'], 'String');
      }
      if (data.hasOwnProperty('toelichting')) {
        obj['toelichting'] = ApiClient.convertToType(data['toelichting'], 'String');
      }
      if (data.hasOwnProperty('zaakgeometrie')) {
        obj['zaakgeometrie'] = ApiClient.convertToType(data['zaakgeometrie'], Object);
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * URL naar het zaaktype in de CATALOGUS waar deze voorkomt
   * @member {String} zaaktype
   */
  exports.prototype['zaaktype'] = undefined;
  /**
   * De datum waarop de zaakbehandelende organisatie de ZAAK heeft geregistreerd
   * @member {Date} registratiedatum
   */
  exports.prototype['registratiedatum'] = undefined;
  /**
   * 
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK.
   * @member {String} zaakidentificatie
   */
  exports.prototype['zaakidentificatie'] = undefined;
  /**
   * Een toelichting op de zaak.
   * @member {String} toelichting
   */
  exports.prototype['toelichting'] = undefined;
  /**
   * Punt, lijn of (multi-)vlak geometrie-informatie, in GeoJSON.
   * @member {Object} zaakgeometrie
   */
  exports.prototype['zaakgeometrie'] = undefined;
  /**
   * Indien geen status bekend is, dan is de waarde 'null'
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


